services:
  - type: web
    name: developer-feedback-dashboard
    runtime: node
    plan: free
    branch: master
    autoDeploy: true
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
